package com.android.mohammadhf.thisorthat.model;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "ANSWER".
*/
public class answerDao extends AbstractDao<answer, Long> {

    public static final String TABLENAME = "ANSWER";

    /**
     * Properties of entity answer.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Choose_answer = new Property(1, String.class, "choose_answer", false, "CHOOSE_ANSWER");
        public final static Property Other_answer = new Property(2, String.class, "other_answer", false, "OTHER_ANSWER");
    }


    public answerDao(DaoConfig config) {
        super(config);
    }
    
    public answerDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"ANSWER\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"CHOOSE_ANSWER\" TEXT," + // 1: choose_answer
                "\"OTHER_ANSWER\" TEXT);"); // 2: other_answer
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"ANSWER\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, answer entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String choose_answer = entity.getChoose_answer();
        if (choose_answer != null) {
            stmt.bindString(2, choose_answer);
        }
 
        String other_answer = entity.getOther_answer();
        if (other_answer != null) {
            stmt.bindString(3, other_answer);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, answer entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String choose_answer = entity.getChoose_answer();
        if (choose_answer != null) {
            stmt.bindString(2, choose_answer);
        }
 
        String other_answer = entity.getOther_answer();
        if (other_answer != null) {
            stmt.bindString(3, other_answer);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public answer readEntity(Cursor cursor, int offset) {
        answer entity = new answer( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // choose_answer
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2) // other_answer
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, answer entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setChoose_answer(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setOther_answer(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(answer entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(answer entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(answer entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
