package com.android.mohammadhf.thisorthat.model;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.android.mohammadhf.thisorthat.model.answer;

import com.android.mohammadhf.thisorthat.model.answerDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig answerDaoConfig;

    private final answerDao answerDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        answerDaoConfig = daoConfigMap.get(answerDao.class).clone();
        answerDaoConfig.initIdentityScope(type);

        answerDao = new answerDao(answerDaoConfig, this);

        registerDao(answer.class, answerDao);
    }
    
    public void clear() {
        answerDaoConfig.clearIdentityScope();
    }

    public answerDao getAnswerDao() {
        return answerDao;
    }

}
